### ISSUE TITLE
how can i use one redmon to monitor multiple servers ？

### ISSUE THREAD

**Issue by 12343954** [steelThread/redmon#23]
Thank you so much ,  bro !

---

but how can i use a redmon to monitor multiple servers ？ like Redis-Live
It looks like it can only monitor one server.

  class Config
    DEFAULTS = {
      :web_interface => ['0.0.0.0', 4567],
      :redis_url     => ['redis://192.168.2.73:6379','redis://192.168.2.73:63791'], //error  :(
      :namespace     => 'redmon',
      :worker        => true,
      :poll_interval => 10
    }

**Comment by bymaximus** [comment]
Still no way to monitor multiple redis servers? Maybe allow us to change it at top bar redis address?
