### ISSUE TITLE
Error on startup - Error undefined method `start' for Thin::Server:Class

### ISSUE THREAD

**Issue by sehreinfach** [steelThread/redmon#63]
OS: CentOS 6.5
Ruby: ruby 1.9.3p484
Install: followed this steps https://gist.github.com/alexandrerocco/6159683

When I try to start _redmon_ the following error occurs:

_Can't start Redmon::App. port in use?  Error undefined method `start' for Thin::Server:Class_

Nothing is listening on port 4567 (checked with _lsof_ and _netstat_). Even when i try to change the port (-p 9876) i get the same error.

**Comment by armata** [comment]
I'm having the same problem on Debian 8.7 x64 on DigitalOcean. I was able to fix it by downgrading to This 1.6.1 (same what @sehreinfach did).
