### ISSUE TITLE
How to run from thin?

### ISSUE THREAD

**Issue by jmmills** [steelThread/redmon#78]
Need to be able to configure a prefix for the service so that it operates properly from behind a proxy (nginx), this is supported from thin, but not from the redmon cli script.

**Comment by jmmills** [comment]
The real issue here is when running from behind a proxy_pass from nginx the path to static content is wrong... for example:

    location /redmon/ {
       proxy_pass http://localhost:4567; # redmon server
    }

Then when you try for http://$nginx_host/redmon/ none of the JS or CSS files have the right path.

**Comment by steelThread** [comment]
Never put redmon behind nginx.  I'll play around with it over the weekend.  Thanks!

**Comment by jmmills** [comment]
I ended up creating my own config.ru for rack that accepts an env variable for mount point:


[config.ru | uploaded via ZenHub](https://files.zenhub.io/553ea31db285bae538013613)

[app.rb | uploaded via ZenHub](https://files.zenhub.io/553ea327b285bae538013614)

**Comment by krsyoung** [comment]
@jmmills are you still using your solution?  I'm stuck in the same boat trying to figure out the right path forward.  I'm making use of the redmon docker image so ideally I can get support directly into redmon itself.

I created a [fork](https://github.com/krsyoung/redmon/tree/add_proxy_option) which adds a new option called `--base-path` to `bin/redmon`.  If it is specified it will then mount the server at the path (i.e. `redmon --base-path '/redmon'` would mount the server at http://somehost/redmon).  Assets will properly load.  

Thoughts?  @steelThread you interested in taking a pull request?

**Comment by jmmills** [comment]
I'm not, iirc I ended up just pointing ops to the port it was running on. I'll double check on Monday if I remember.


Thanks,
   Jason Mills

- sent from mobile.

**Comment by steelThread** [comment]
@krsyoung - sure!

**Comment by krsyoung** [comment]
Excellent, round 1 submitted:  https://github.com/steelThread/redmon/pull/85

Thanks @steelThread!

**Comment by krsyoung** [comment]
Cool, this is merged and looking good.  Thanks @steelThread, any thoughts on cutting a new version of the gem?

**Comment by steelThread** [comment]
Thanks for validating.  I'll publish a little later today.

**Comment by steelThread** [comment]
[Done!](https://rubygems.org/gems/redmon)

**Comment by steelThread** [comment]
Let me know if that works for you @krsyoung

**Comment by krsyoung** [comment]
After a week of testing things are looking perfect.  Thanks again @steelThread!   👌
