### ISSUE TITLE
cut a new version of the gem?

### ISSUE THREAD

**Issue by amatriain** [steelThread/redmon#93]
There are several merged PRs since september that are not yet included in a released version. One of them, the removal of activesupport dependency, is necessary to update any rails apps that include redmon in the bundle to rails 5.

Could you consider cutting a new version of the gem and publishing in rubygems?

**Comment by steelThread** [comment]
Will try this evening.  eventmachine(1.0.0) is failing compilation for me, need to resolve that first.

**Comment by steelThread** [comment]
Still working on this.  I've upgraded all the dependent gems.  Small issue with signal handling that I need to resolve.  sorry for the delay.

**Comment by steelThread** [comment]
[done](https://rubygems.org/gems/redmon).  let me know if there are any issues.
